runtime: nodejs20
service: default

env_variables:
  NODE_ENV: production
  NEXT_PUBLIC_API_URL: https://igdb-api-staging-d6xpjrmqsa-ew.a.run.app

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: node Sync/Utveckling/IGDB/web_app/frontend/server.js
